name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node-version: [10.x,12.x,14.x]
       site: [dev,test,prod]
       include:
         - node-version: 13.x
         - site: "val"
           datacenter: "site-a"
         - node-version: 12.x
           site: "qa"
           datacenter: "site-c"
    steps:
      - name: Echo site details
        env:
          SITE: ${{ matrix.site }}
          DATACENTER: ${{ matrix.datacenter }}
        run: echo $SITE $DATACENTER
