name: Node.js CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo site details
        env:
          REF: ${{ github.ref }}
        run: echo $GITHUB $DATACENTER
