name: Node.js CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id : step1
        env:
          REF: ${{ github.ref }}
        run: |
             echo $GITHUB_REF 
             echo $REF 
      - name: step2
        env:
          REF: ${{ steps.step1.outcome }}
        run: |
             echo $STEPS_STEP1_CONCLUSION 
             echo $REF 
