name: Node.js CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - name: step2
        env:
          REF: ${{ steps.checkout.outcome }}
        run: |
             echo $STEPS_STEP1_CONCLUSION 
             echo $REF 
